### ISSUE TITLE
Add to mkdocs wiki plugin overview

### ISSUE THREAD

**Issue by timvink** [mkdocs/mkdocs-click#40]
Nice plugin!

I actually wish I'd discovered it earlier. Can I suggest you add the plugin to the overview here: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins. It will help visibility :)

Perhaps useful for this plugin as well, the approach I took is using mkdocs-macros to insert the output of some_click_command --help into my mkdocs folder. Relevant code bits:

- mkdocs.yml section: https://github.com/ing-bank/doing-cli/blob/main/mkdocs.yml#L76-L79 
- env function: https://github.com/ing-bank/doing-cli/blob/cb76280ad0b2f30091dcd04a1737fa18e5a9428c/src/doing/utils.py#L219-L232
- insertion into a .md page: https://github.com/ing-bank/doing-cli/blame/main/docs/reference/manual/list.md#L29-L33

**Comment by oprypin** [comment]
It is there https://github.com/mkdocs/catalog#-api-documentation-building
