### ISSUE TITLE
Documentation only renders when there are at least two spaces at the end of .md file

### ISSUE THREAD

**Issue by ieaves** [mkdocs/mkdocs-click#50]
I'm a new user to `mkdocs-click` so apologies if I'm doing something wrong but I've been stuck trying to get even the basic Readme example working. I found [this](https://github.com/DataDog/mkdocs-click/issues/46#issuecomment-1040603117) comment in issue #46 which referred to the issue changing when "hitting enter." As it turns out, the CLI documentation will _only_ render for me if there are at least two spaces at the end of the markdown file, otherwise it renders the header but not CLI documentation.

e.g. this will only render the heading `CLI Reference`

```yaml
# CLI Reference

::: mkdocs-click
    :module: app.cli
    :command: cli
```

but this will render the heading and generated documentation.

```yaml
# CLI Reference

::: mkdocs-click
    :module: app.cli
    :command: cli
<newline>
<newline>
```

It's a particular challenge for new users where they are likely to copy / paste the readme example into a new text file in order to begin testing and immediately hit a deadend. In my case, I assumed there was something arcane about the :module: reference (does it follow standard library import hierarchies, are they directory hierarchies, something else, etc...)

**Comment by ofek** [comment]
I think part of the issue is that h1 is set as the CLI's name. Can you try `:depth: 1` or removing header?

**Comment by ieaves** [comment]
Hey @ofek. Sure! Here are a few of the variations I've attempted based on your suggestion

* Changing the h1 label (just `test` in this case), one space at the end of the file, with and without `:depth: 1` tag
* Removing the header, one space at the end of the file, with and without `:depth: 1` tag

None of those work, however, they _all_ work if there are two spaces at the end of the file.

**Comment by sveint** [comment]
I can confirm the issue.

I thought something was misconfigured, but then I found this issue and thought I'd try it out. For me a single newline with no extra characters fixes the problem.

**Comment by miketheartguy** [comment]
I'm getting the same issue on a brand new (empty) project...

Project Structure (`tree -I venv/`):
```
.
├── app
│   ├── cli.py
│   └── __init__.py
├── docs
│   └── index.md
├── mkdocs.yml
└── requirements.txt
```

Copied & Pasted contents of app/cli.py, mkdocs.yml and docs/index.md from [Quickstart](https://github.com/DataDog/mkdocs-click#quickstart) example. 

When running mkdocs serve or build there's no error, but also no content for the mkdocs-click block. 

If I add a newline at the end of the file then I get: **ModuleNotFoundError: No module named 'app'**

**Comment by Gustavo-SF** [comment]
I also had this same issue on macOS 12.4, Python3.10 and mkdocs-click version 0.8.0. 
Fixed it with a double newline at the end.

**Comment by matroscoe** [comment]
I also ran into this issue, if it is required (it is really okay that it is) ideally there would be a check for this at build time (or a note in the README). I spent a fair amount of time banging my head against a wall to find out why I couldn't get my docs to generate. 

Python 3.11, Ubuntu 22.04, mkdocs-click = "^0.8.0"
