### ISSUE TITLE
Can't set up - getting `ModuleNotFoundError`

### ISSUE THREAD

**Issue by Trymzet** [mkdocs/mkdocs-click#64]
Hi, I installed it in my virtual env, getting this error when running `mkdocs serve`:
```
ERROR    -  Config value: 'markdown_extensions'. Error: Failed to load extension 'mkdocs-click'.
            ModuleNotFoundError: No module named 'mkdocs-click'
Aborted with 1 Configuration Errors!
```

The package in installed in the venv and shown when running `pip list`.

Could it be because I'm using a different theme (material) than in the instructions?

**Comment by oprypin** [comment]
I don't know why this is happening, it should work, it must be that the installation with `pip` somehow was not fully done. It is not affected by theme.
