### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by jorgegomezcq** [mkdocs/mkdocs-click#66]
Hi,

Is this project still active and has anyone tested this project with the material theme?

**Comment by oprypin** [comment]
Hi @FlorentClarret @ofek 

I would be interested in maintaining this project - though probably only with bugfixes. Would it be possible to give me rights, or transfer to https://github.com/mkdocs org?
It could be done similarly to https://github.com/mkdocs/mkdocs-redirects/issues/32#issuecomment-1016808112

Alternatively, could you check out issues and pull requests :sweat_smile:

**Comment by ofek** [comment]
You will have to invite me to the org in order for it to allow me to transfer. If it's fine with you I would still like to partially help with maintenance so maybe I could stay afterward?

**Comment by ofek** [comment]
The transfer is complete! For PyPI, what should I do?

**Comment by oprypin** [comment]
Thank you @ofek! Yes sure please stay around :)

Could you please add https://pypi.org/user/oprypin/ as owner

**Comment by ofek** [comment]
Okay I just sent an invite, let me know if that works

**Comment by oprypin** [comment]
Yes that worked too, thank you
